### ISSUE TITLE
Inconsistent time window settings on executive dashboard

### ISSUE THREAD

**Issue by orion84** [splunk/rwi_executive_dashboard#25]
The executive dashboard has several panels looking at 'last 1 hour' in different ways.

Active VPN uses `-1h to now`
Active Zoom uses `-1h@h to @h`
Connected Workforce by Location uses `-1h to @h`

Why use `@h` for panels that are supposed to show active things?

**Comment by l00py** [comment]
@orion84, very good catch! We'll capture this as a bug and implement in the next release.

**Comment by l00py** [comment]
Resolved in 1.1.1
